trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PullLatestImage
  jobs:
  - job: PullLatestImageJob
    steps:
    - bash: docker pull akbarchandani/selenium-docker-linux
- stage: StartGrid
  jobs:
  - job: StartGridJob
    steps:
    - bash: docker-compose up -d hub chrome firefox   